<?php 
defined('C5_EXECUTE') or die(_("Access Denied."));

$options = array(
    array(
        'name' => t("Marketplace"),
        'desc' => t("Choose settings for Marketplace integration"),
        "icon" => 'fa-money',
        'type' => 'section'
    ),
    array(
        "name" => t("Marketplace Enabled"),
        "desc" => t('Enable marketplace integration'),
        "id" => 'concrete-marketplace-enabled',
        "type" => "toggle"
    ),
    array(
        "name" => t("Marketplace Intelligent Search"),
        "desc" => t('Enable intelligent search integration'),
        "id" => 'concrete-marketplace-intelligent_search_help',
        "type" => "toggle"
    ),
    array(
        'name' => t("Concrete5 News"),
        'desc' => t("Choose settings for Concrete5 News integration"),
        "icon" => 'fa-newspaper-o',
        'type' => 'section'
    ),
    array(
        "name" => t("News Overlay"),
        "desc" => t('Display an overlay with up-to-date news from concrete5 once per day'),
        "id" => 'concrete-external-news_overlay',
        "type" => "toggle"
    ),
    array(
        "name" => t("Concrete5 News"),
        "desc" => t('Enable concrete5 news within your site'),
        "id" => 'concrete-external-news',
        "type" => "toggle"
    ),
    array(
        'name' => t("white Label"),
        'desc' => t("Personalize the CMS itself"),
        "icon" => 'fa-magic',
        'type' => 'section'
    ),
    array(
        "name" => t("Concrete5 Logo"),
        "desc" => t('Absolute path to custom Concrete5 Logo. Image should be 23px width & height.'),
        "id" => 'concrete-white_label-logo',
        "type" => "file",
        "filetype" => "image" ,
        "default" => 0       
    ),
    // array(
    //     "name" => t("Concrete5 Login Background"),
    //     "desc" => t('Choose a logo to replace the Concrete5 Logo. Image should be 23px height'),
    //     "id" => 'concrete-urls-background_url',
    //     "type" => "file",
    //     "filetype" => "image",
    //     "default" => 0
    // ),
    array(
        "name" => t("Concrete5 Name"),
        "desc" => t('The name of the CMS'),
        "id" => 'concrete-white_label-name',
        "type" => "text",
        "size" => "60"
    ),
    array(
        'name' => t("Misc"),
        'desc' => t("A section for miscalenous settings"),
        "icon" => 'fa-star',
        'type' => 'section'
    ),
    array(
        "name" => t("Default jpeg image compression"),
        "desc" => t("This setting allow you to control the quality of thumbnails generated by Concrete5. Big valu create nice image but slow loading"),
        "id" => "concrete-misc-default_jpeg_image_compression",
        "min" => 20,
        "max" => 100,
        "step" => 2,
        "unit" => '',
        "type" => "range"
    ),
    // -- Submit -- \\
    
    array(
        'type' => 'submit',
        'name' => t("Save"),
        'id' => 'saved'
    )
);
if (!isset($passThrough))
new Concrete\Package\ThemeSupermint\Src\Helper\OptionsGenerator($options, null, $this->action('save_site_settings'), false, $options_saved);
